# Add 'label1' to any changes within 'example' folder or any subfolders
Backend:
- backend/**

Frontend:
-frontend/**

# Add 'label2' to any file changes within 'example2' folder
Symfony: symfony-docker/*
