# Use an official Python runtime as the parent image
FROM python:3.9-slim

# Copy the current directory contents into the container at /app
COPY . ./

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable for further use
# For example, if you have a production environment, you'd set it here
# ENV NAME World

# Run the application when the container launches
CMD ["python", "/app/data_parser.py"]
